### PR TITLE
Add token expiration to SecurityResourceProperties

### PR DESCRIPTION
**Pull request by andreassiegel**
### What changes were proposed in this pull request?

Adds to new configuration parameters to configure the expiration of access tokens and refresh tokens:
```
smartcosmos:
  security:
    resource:
      accessTokenValiditySecs: 43200
      refreshTokenValiditySecs: 2592000
```

By default, we use the same values Spring provides:
- access token expiration: 12 hours
- refresh token expiration: 30 days

### How is this patch documented?

Code

### How was this patch tested?

manually using Postman

#### Depends On

Nothing

### CODE REVIEW

**Review by tcrossrfid — APPROVED** [review]
LGTM

**Comment by voor** [comment]
What do you guys think of just moving this class into the Auth Server?  Seems pretty pointless to keep it in Framework, since the configuration is 100% for the Auth Server.

**Comment by andreassiegel** [comment]
Yeah! I agree, especially since I looked for the class in the `auth-server` project.

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
